posco:
    name: 3기dev
    count: 20
    datasource:
        url: jdbc:mysql://localhost:3306/rollin?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: 1234
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rollin?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: "{cipher}0f0d9c5f72076801294d5837ed83c489046041e1a8cb60dbc9684ef9dcc45154"

jwt:
    secret_key: SECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEY
    expTime: 8640000
